//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuickFood.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class client
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public client()
        {
            this.commande = new HashSet<commande>();
        }
    
        public int idclient { get; set; }
        [Required]
        public string nom_pre_client { get; set; }
        [Required]
        [Range(10000000, 99999999)]
        public string tel_client { get; set; }
        [Required]
        public string adr_cl { get; set; }
        [Required]
        [EmailAddressAttribute]
        public string email_cl { get; set; }
        public Nullable<System.DateTime> date_nai_cl { get; set; }
        [Required]
        public string sexe_cl { get; set; }
   
        public int id_ville { get; set; }
    
        public virtual ville ville { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<commande> commande { get; set; }
    }
}
