//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuickFood.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class detail_cmd
    {
        public int id_ds { get; set; }
        public int id_cmd { get; set; }
        public int id_platss { get; set; }
        public Nullable<int> quantite { get; set; }
    
        public virtual commande commande { get; set; }
        public virtual platss platss { get; set; }
    }
}
