//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuickFood.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class trace_liv
    {
        public int id_trace { get; set; }
        public string date_liv { get; set; }
        public string heure_liv { get; set; }
        public string date { get; set; }
        public Nullable<int> id_liv { get; set; }
    
        public virtual livreur livreur { get; set; }
    }
}
